repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.7
    hooks:
      - id: ruff # Linter
        args: [--fix]
      - id: ruff-format # Formatter
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: uv run python -m pytest
        language: system
        types: [python]
        pass_filenames: false
